apiVersion: v1
kind: Service
metadata:
  name: email-pre-processing-service-service
  labels:
    app: email-pre-processing-service
spec:
  type: NodePort
  ports:
  - port: 7000
    protocol: TCP
  selector:
    app: email-pre-processing-service
